---
title: "various_mthods_fc"
author: "Elvis Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(fpp3)
```


```{r}
employ<- read.csv("ABSemp.csv")
```




# Type 

```{r}
  
  
ts_employ <- employ |> 
    mutate(Quarter = yearquarter(my(Date))) |> 
    select(-Date) |> 
    as_tsibble(index = Quarter) 

pre_2020 <- ts_employ |> 
  filter(Quarter <= yearquarter("2020 Q1"))

```


# Split the test and training set 

```{r}

training <- pre_2020[1:120,] 

test <- pre_2020[121:nrow(pre_2020),]
```




# pivot into longer format 


  



```{r}

orlong <- ts_employ |> 
  pivot_longer(cols = c(-Quarter) , names_to = "Industry", values_to = "Employment")

training <- training |> 
  pivot_longer(cols = c(-Quarter) , names_to = "Industry", values_to = "Employment")

test <- test |> 
  pivot_longer(cols = c(-Quarter) , names_to = "Industry", values_to = "Employment")

```




# Conduct the forecast 

```{r}
fc_model <- ts_employ |> 
  model(stepwise = ARIMA(Employment), 
        ets = ETS(Employment), 
        mean = MEAN(Employment))


fc_emp<- fc_model |> 
  forecast(h=22)


error <-  fc_emp |> 
  accuracy(orlong)#%>%
  select(.model, MAPE)


```

# Check the error measurement 



```{r}
ETS_mod <- error |> 
  filter(.model == "ets")

ETS_MAPE <- colSums(as.matrix(ETS_mod$MAPE)) / nrow(ETS_mod)

ETS_MASE <- colSums(as.matrix(ETS_mod$MASE)) / nrow(ETS_mod)
```



```{r}
ARIMA_mod <- error |> 
  filter(.model == "stepwise")

ARIMA_MAPE <- colSums(as.matrix(ARIMA_mod$MAPE)) / nrow(ARIMA_mod)

ARIMA_MASE <- colSums(as.matrix(ARIMA_mod$MASE)) / nrow(ARIMA_mod)

```




```{r}
MEAN_mod <- error |> 
  filter(.model == "mean")

MEAN_MAPE <- colSums(as.matrix(MEAN_mod$MAPE)) / nrow(MEAN_mod)


MEAN_MASE <- colSums(as.matrix(MEAN_mod$MASE)) / nrow(MEAN_mod)

MEAN_RMSE <- colSums(as.matrix(MEAN_mod$RMSE)) / nrow(MEAN_mod)

```


