---
chapter: 1
knit: "bookdown::render_book"
---

# The Australian COVID-19 Pandemic Background

The COVID-19 pandemic has had a massive impact on global economies. Millions of workers have been furloughed or even fired across the globe as businesses struggled to survive [@ny2020]. The same situation occurred in Australia, due to increased restrictions, many businesses closed their doors, while employees worked few hours or were laid off by businesses. As a result of the continued "lockdown" periods in 2020, the Australian Bureau of Statistics [@ABS2021] estimated that 72% of businesses generated less revenue and the underemployment rate reached a historical high of 13.8% by the end of April, 2020, only one month after the outbreak of COVID-19. 

Our research is motivated by the lack of quantitative research on the employment of two-digit disaggregated industry subsectors in Australia, despite the fact that many studies have focused on the aggregated employment rate. The loss of hierarchical information is a common issue with aggregated studies, which can lead to biased conclusions or the illusion of prosperity in the labour market. In this manner, a quantitative analysis of sectoral employment will alleviate this problem, allowing us to better assess the effects of COVID-19 in Australia.





## Research Aim and questions 



This research will expand on @anderson2020 by using data from 87 two-digit industry sectors rather than the 19 sectors that they used previously. I will develop a model for the two-digit subsectors to assess the long run effect and the COVID-19 post-impacts. In addition, I will present a counterfactual analysis based on the optimistic assumption that no COVID-19 or major events occurred. The two-digit sectoral data will provide us with more valuable information, allowing us to gain a deeper understanding of employment dynamics in Australia at a disaggregated level.


The overall goal of the research is to provide estimates of two-digit sectoral employment based on historical data. My specific objectives are as follows: 

1. Create a time series model of employment in 84 two-digit subsectors of the Australian economy.

1. To conduct a counterfactual analysis using this model. 

3. To use this model to determine which two-digit subsectors have the highest long-term impact (or positive spillover) on employment growth in the long run.



## Thesis Structure 


This thesis examines Australian Employment at a disaggregated level before estimating the long run effects of COVID-19 on the sectoral employment rate in Australia. The rest of the thesis is organised as follows. First, in chapter 2, I begin by reviewing the existing literature in the relevant fields. Second, in chapter 3, I will provide data sources as well as an exploratory data analysis. Then, in chapter 4, I will present our selected model. After we have chosen our model, I will conduct a counterfactual analysis to assess the impact of COVID-19 and provide useful insights on key beneficial industries after COVID-19 in chapter 5. Finally, in chapter 6, I will provide a brief conclusion and discuss the limitations and potential future extensions. 





\clearpage


