---
chapter: 5
knit: "bookdown::render_book"
---


# Timeline for Honours 2022

Table \ref{tab:timeline1} summaries the work done to date. Table \ref{tab:timeline2} maps out the plan for completing the thesis research.

```{r timeline, results='asis', echo = F}
timeline = data.frame(Timeline = c("Week 2","Week 3","", "Week 4","", "Week 5", "Week 6", "Week 7","Week 8", "week 9"),
                      Tasks = c(" Background reading about Multivariate VAR model",
                                "Collect two-digit subsectoral data from ABS website",
                                "Prepare materials reltaed to two-digit subsectoral employment evaluations",
                                "Prepare literature review related to BVAR model and setting priors",
                                "Analysis about the MATLAB code done by Andereson et al. (2020)",
                                "Read articles about Conditional Forecasting",
                                "Prepare the conditional forecasting coding and hierarchical forecasting",
                                "Exploratory data analysis on sectoral and two-digit subsectoral data",
                                "Select suitable plots and test softwares to prepare the proposal ",
                                "Write research proposal and prepare the first presentation"))


knitr::kable(timeline, "latex",
             caption = "Completed work",
             label = "timeline1",
             booktabs = TRUE,
             escape = FALSE)
  
```

```{r, echo = F, fig.height=80}
timeline = data.frame(Timeline = c("June - July", "August", "September", "October"),
                      Tasks = c("Modelling of two-digit subsectoral employment", "Train the model using pre-covid data with BVAR model and compare the accuracy with other models","apply forecasts using BVAR , conduct both conterfactual analysis and sectoral multiplier analysis", "Write my thesis and prepare for the second presentation")) 

knitr::kable(timeline, "latex",
             caption = "Research plan",
             label = "timeline2",
             booktabs = TRUE,
             escape = FALSE) 
```



