---
title: 'Disaggregated Sectoral Employment Dynamics in Australia'
degreetype: 'Bachelor of Commerce (Honours)'
author: 'Zhixiang Yang'
studentid: 30306396
output: bookdown::pdf_book
site: bookdown::bookdown_site
link-citations: yes
knit: "bookdown::render_book"
---

<!-- 
This file should be left empty other than the header above.

The thesis contents are contained in the other Rmd files: `01-chap1.Rmd `, `02-chap2.Rmd`, `A-appA.Rmd`, etc. Add new Rmd files as required. You'll need to edit the `_bookdown.yml` file to set the order in which you'd like them to appear.

If you have specific LaTeX packages to add, put them in `monashthesis.tex`.

You will need to ensure you have installed the `knitr` and `bookdown` packages for R.

You will also need LaTeX installed on your computer.
-->






# Acknowledgement {-}

I would like to express gratitude to my supervisor Professor Farshid Vahid and my coordinator Professor Heather M Anderson for their selfless support and devoted care along the way. I would also like to thank my family and Xiefei Li for their continuous supports and encouragement. 



\vspace{48pt}

`Matlab version. 2022a` codes are used to generate the estimated coefficients for the proposed Bayesian VAR model.

R `4.1.2 "Bird Hipple"` [@R] and Rstudio `2022.07.1+554 "Spotted Wakerobin"` [@Rstudio] are used for data analysis in this thesis. 

\vspace{12pt}

R package used and their versions in this research include `matrixStats 0.61.0` [@package_matrixStats], `ggplot2 3.3.5` [@package_ggplot2], `zoo 1.8.9` [@zoo], `tidyverse 1.3.1` [@tidyverse], `dplyr 1.0.8` [@dplyr], `stats 4.1.2` [@stats], `readr 2.1.2` [@readr], `pracma 2.3.8` [@pracma], `lubridate 1.8.0` [@lubridate], `fpp3 0.4.0` [@fpp3], `ggpubr 0.4.0`[@ggpubr], `ggrepel 0.9.1` [@ggrepel], `directlabels 2021.1.13` [@directlabels], `gghighlight 0.3.3` [@gghighlight]. 
(*Note: In no particular order above*)


\vspace{12pt}


This thesis is produced using the R package `bookdown 0.25` [@bookdown] with the Rmarkdown template package `monash 0.0.0.9000` for the honours thesis in the Department of Econometrics and Business Statistics, Monash University [@monash]






# Declaration {-}


I declare that this thesis contains no material which has been submitted in any form for the award of any other degree or diploma in any university or equivalent institution, and that, to the best of my knowledge and belief, this thesis contains no material previously published or written by another person, except where due reference is made in the text of the thesis. 

\vspace{12pt}


-- Signature: \underline{\emph{\textbf{Elvis Zhixiang Yang}}}

# Abstract {-}


I investigate the performance of Australian employment at a disaggregated level and compare the post-COVID situation with the no-COVID situation. The outcomes are generated via a series of appropriate forecasting methods. A multivariate time series model is utilised to determine the long run employment spillovers to the total employment at the two-digit subsectoral level. My results suggest that in the two-digit subsectoral level, `Other Store-Based Retailing`, followed by `Administrative Services`, `Furniture and Other Manufacturing` will generate the strongest positive spillovers to the total economy. One of the main contributions of this paper is that the government can stimulate these high and positive spillovers to recover total employment effectively and efficiently. Moreover, I evaluate the impacts of COVID-19 on the Australian labour market with counterfactual analysis. The outcomes demonstrate that the pandemic has a long-lasting effect on the economy. In addition, I point out the main reason behind the lowest unemployment rate record and compare the no-COVID scenario for unemployment rate. The spillover analysis together with the evaluation, thus, provide another aspect for policymarkers to improve the Australian economy. 




<!-- Moreover, I provide an intuitive evaluation of the changes in Australia after COVID-19 happened. I have concluded that the impacts COVID-19 to the Australian labour market is continuing and will not recover in the foreseen future. Thus, together with the spillover analysis, this thesis will provide more useful information for policymakers.  -->


